require.config({
	baseUrl: "../scripts",
	paths: {	
		async : 'lib/async',
		goog : 'lib/goog',
		propertyParser : 'lib/propertyParser',
		jqueryUI: 'lib/jquery-ui/jquery-ui.min',
		jquery: 'lib/jquery-2.1.4.min',
		smoke: 'SmokeTimer',
		statcrack: 'StatCrack',
		windowCoreFunctions: 'assets/windowCoreFunctions',
		appSettings: 'settings',
		refreshHUD: 'assets/refreshHUD',
		recording: 'assets/recording',
		main: 'main',
		HSpercent: 'HSpercent',
		HScounter: 'HSCounter',
		HSchains: 'HSChains',
		gearData: 'assets/gearData',
		gameEvent: 'assets/gameEventHandler',
		updateData: 'assets/updateData',
		settingHelper: 'assets/settingHelper',
		calcData: 'assets/calcData',
		graph: 'assets/graph',
		arrayData : 'assets/arrayData',
		sync: 'assets/sync',
		gearDisplay: 'assets/gearDisplay',
		printArmorTab: 'assets/printArmorTab',
		repairCalc: 'assets/repairCalc',
		htmlInjection: 'assets/htmlInjection',
		counters: 'assets/counters',
		launchManager: 'assets/launchManager',
		localStorageInit: 'assets/localStorageInit',
		spectrum: 'lib/spectrum',
		crosshair: 'crosshair',
		popup: 'popup',
		recordingMenu: 'recordingMenu',
		KPminute: 'KPminute',
		info: 'Info',
		recCount: 'recCount',
	}
});